pipeline {
    agent any
        stages {

           stage("Report"){
                 steps {
                    sh  ''' echo 'Code Coverage'
                            coverage run natural_language_processing/tests/test_dataset_hdfs.py
                            coverage report
                            coverage xml -o natural_language_processing/tests/reports/coverage.xml
                        '''
                        }
                post{
                    always{
                            step([$class: 'CoberturaPublisher',
                                   autoUpdateHealth: false,
                                   autoUpdateStability: false,
                                   coberturaReportFile: 'natural_language_processing/tests/reports/coverage.xml',
                                   failNoReports: false,
                                   failUnhealthy: false,
                                   failUnstable: false,
                                   maxNumberOfBuilds: 10,
                                   onlyStable: true,
                                   sourceEncoding: 'ASCII',
                                   zoomCoverageChart: true])
                   }
               }
        }
    }
}
