pipeline {
    agent any
        stages {
            stage ('Build') {
                   steps{
                        sh 'export PYTHONPATH="${PYTHONPATH}:/var/lib/jenkins/workspace/DeepLearningPipeline_job_/natural_language_processing"'
                        }
                    steps {
                        echo 'Running build phase. '
                        sh   '''python natural_language_processing/data/start_data_pipeline.py
                                python natural_language_processing/model/model.py'
                               '''
                        }
                }
           stage("Report"){
                 steps {
                    sh  ''' echo 'Code Coverage'
                            coverage run natural_language_processing/tests/test_datasets_hdfs.py
                            coverage report
                            coverage xml -o natural_language_processing/tests/reports/coverage.xml
                        '''
                        }
                post{
                    always{
                            step([$class: 'CoberturaPublisher',
                                   autoUpdateHealth: false,
                                   autoUpdateStability: false,
                                   coberturaReportFile: 'natural_language_processing/tests/reports/coverage.xml',
                                   failNoReports: false,
                                   failUnhealthy: false,
                                   failUnstable: false,
                                   maxNumberOfBuilds: 10,
                                   onlyStable: true,
                                   sourceEncoding: 'ASCII',
                                   zoomCoverageChart: true])
                   }
               }
        }
    }
}
